---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart wal-g backup timer
  ansible.builtin.systemd_service:
    name: "{{ wal_g_backup_service_name }}.timer"
    state: restarted
    enabled: true
  when: wal_g_enable_full_backup_timer | bool

- name: Restart postgresql
  ansible.builtin.systemd_service:
    name: "{{ wal_g_postgresql_service_name }}"
    state: restarted
